add spc to water flag
prody/ProDy pull request #1953
Opened 2024-09-13 15:09 UTC by jamesmkrieger

Otherwise, resname SPC is not selected as water

2024-09-18 10:55 UTC, jamesmkrieger commented
We now have selections working e.g.
```
In [1]: from prody import *

In [2]: ag = parsePDB('ionized2_swap.pdb', long_resname=True)
@> 461487 atoms and 1 coordinate set(s) were parsed in 5.64s.

In [3]: set(ag.ion.getResnames())
Out[3]: {'CLA', 'CU2P', 'SOD'}

In [4]: set(ag.ion.getNames())
Out[4]: {'CLA', 'CU2P', 'SOD'}

In [5]: set(ag.water.getResnames())
Out[5]: {'SOL'}

In [6]: set(ag.water.getNames())
Out[6]: {'HW1', 'HW2', 'OW'}

In [7]: ag = parsePDB('ionized2_swap.pdb')
@> 461487 atoms and 1 coordinate set(s) were parsed in 5.74s.

In [8]: set(ag.ion.getResnames())
Out[8]: {'CLA', 'CU2', 'SOD'}

In [9]: set(ag.water.getNames())
Out[9]: {'HW1', 'HW2', 'OW'}

In [10]: set(ag.ion.getNames())
Out[10]: {'CLA', 'CU2P', 'SOD'}
```

2025-07-17 19:51 UTC, AnthonyBogetti commented
@karolamik13 did you have a chance to test this?

2025-07-17 20:44 UTC, karolamik13 commented
> @karolamik13 did you have a chance to test this?

No, but I will do it now.

2025-07-17 21:13 UTC, karolamik13 reviewed
I tested water/ion and long resname:
In [1]: from prody import *

In [2]: a = parsePDB('test.pdb', long_resname=True)
@> 7033 atoms and 1 coordinate set(s) were parsed in 0.09s.

In [3]: set(a.ion.getResnames())
Out[3]: {'CLA', 'CU2P', 'SOD'}

In [4]: set(a.water.getResnames())
Out[4]: {'SOL', 'SPC', 'TIP'}

In [5]: a = parsePDB('test.pdb')
@> 7033 atoms and 1 coordinate set(s) were parsed in 0.15s.

In [6]: set(a.ion.getResnames())
Out[6]: {'CLA', 'CU2', 'SOD'}

In [7]: set(a.water.getResnames())
Out[7]: {'SOL', 'SPC', 'TIP'}


Tomorrow I will test watFinder.

2025-07-18 09:22 UTC, karolamik13 commented
I was looking at WatFinder using the structure provided by James (ionized2_swap_sel.pdb) where we have copper, 2 water molecules (SOL) in between two protein chains. The result is below, so I am not able to detect inetractions. I am not sure why. James, any suggestions? Maybe I should do something with additional parameters? If so we should definitely show such cases in tutorials.

In [1]: from prody import *

In [2]: p = parsePDB('ionized2_swap_sel.pdb', long_resname=True)
@> 24451 atoms and 1 coordinate set(s) were parsed in 0.25s.

In [3]: wb_ens = calcWaterBridges(p, output='info', considered_atoms_sel='protein or resname CU2P')
@> 0 water bridges detected using method chain

In [4]: wb_ens = calcWaterBridges(p, output='info')
@> 0 water bridges detected using method chain

In [5]: p.ion.getResnames()
Out[5]: array(['CU2P'], dtype='<U6')

In [6]: p.water.getResnames()
Out[6]: array(['SOL', 'SOL', 'SOL', 'SOL', 'SOL', 'SOL'], dtype='<U6')

2025-07-18 09:44 UTC, karolamik13 reviewed
New update, with such command, it will detect ions:

In [13]: calcWaterBridges(p, output='info', considered_atoms_sel='protein or ion', donors=['N', 'O', 'S', 'F', 'CU2P'], acceptors=['N', 'O', 'S', 'F', 'CU2P'
    ...: ], selstr='all within 12 of resname CU2P')
@> 1 water bridges detected using method chain
@> CU2P9120 CU2P_537  GLY235 N_264 B 4.940425082925553 1 ['_531']
Out[13]: 
[['CU2P9120',
  'CU2P_537',
  '',
  'GLY235',
  'N_264',
  'B',
  4.940425082925553,
  1,
  ['_531']]]

I am not sure what to do it water.

2025-07-18 10:02 UTC, jamesmkrieger commented
> New update, with such command, it will detect ions:
> 
> In [13]: calcWaterBridges(p, output='info', considered_atoms_sel='protein or ion', donors=['N', 'O', 'S', 'F', 'CU2P'], acceptors=['N', 'O', 'S', 'F', 'CU2P' ...: ], selstr='all within 12 of resname CU2P') @> 1 water bridges detected using method chain @> CU2P9120 CU2P_537 GLY235 N_264 B 4.940425082925553 1 ['_531'] Out[13]: [['CU2P9120', 'CU2P_537', '', 'GLY235', 'N_264', 'B', 4.940425082925553, 1, ['_531']]]
> 
> I am not sure what to do it water.

This is a result of having water in between. I think this is the expected behaviour.

The usual tools for analysing water clustering in between should hopefully work. I've just sent you a trajectory so you can try that

2025-07-18 11:14 UTC, karolamik13 requested changes
New test below. Looks good. The only thing I would change is the lack of water type name in the results.

In [7]: p = parsePDB('ionized2_swap_sel.pdb', long_resname=True)
@> 24451 atoms and 1 coordinate set(s) were parsed in 0.26s.

In [8]: calcWaterBridges(p, output='info', considered_atoms_sel='protein or ion', donors=['N', 'O', 'S',
   ...: 'F', 'CU2P'], acceptors=['N', 'O', 'S', 'F', 'CU2P'], selstr='all within 12 of resname CU2P')
@> 3 water bridges detected using method chain
@> HISD234 NE2_259 B GLY235 N_264 B 4.417386104926755 1 ['_531']
@> CU2P9120 CU2P_537  GLY235 N_264 B 4.940425082925553 1 ['_531']
@> CU2P9120 CU2P_537  HISD234 NE2_259 B 2.2886458878559623 1 ['_531']
![copper_system](https://github.com/user-attachments/assets/e69ece3d-e95b-4aaa-9239-bba7775f5f9f)

2025-07-18 11:24 UTC, jamesmkrieger commented
Can you give an example of what the output looks like in the regular protein and water case where we see the water type?

2025-07-18 11:29 UTC, karolamik13 commented
You can find it here:
http://www.bahargroup.org/prody/tutorials/watfinder_tutorial/singlePDB.html

@> SER7 OG_21 A ARG40 NH1_285 A 4.900955519079926 1 ['A_1289']
@> SER7 OG_21 A LYS110 NZ_838 A 4.70722699686344 1 ['A_1316']
@> GLY14 O_72 A GLU50 N_347 A 4.544135231262378 1 ['A_1274']
@> GLY14 O_72 A SER47 O_328 A 5.288116583434976 1 ['A_1274']

Now I see it was chain name and not water name.

2025-07-18 11:32 UTC, jamesmkrieger commented
Oh, I see. It may be that this pdb file has no chain id for the water

2025-07-18 11:37 UTC, karolamik13 approved these changes

2025-07-18 11:38 UTC, karolamik13 commented
> Oh, I see. It may be that this pdb file has no chain id for the water

You are right. Water molecules are without chain name in this PDB.

2025-07-18 14:46 UTC, AnthonyBogetti commented
Thank you, James and Karolina. Please merge if this is ready.

2025-07-18 15:03 UTC, merged